
#These are the mandatory fields
#which needed to add into properties file
#of target application

#spring.application.name=my-app
#spring.data.redis.host=<redis-host-ip>
#spring.data.redis.port=<redis-host-port>
#spring.data.redis.username=<if secure>
#spring.data.redis.password=<if secure>